#!/bin/bash
apt-get update
puppet resource package git ensure=present

puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running

puppet resource file /tmp/6537987f/research ensure=absent force=true
puppet resource file /tmp/6537987f/research ensure=directory


cd /tmp/6537987f/research/
git clone https://github.com/Samathullah/6537987f_op_repo.git
cp -p /tmp/6537987f/research/6537987f_index.html /var/www/html/index.html
